- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: copy expense config file
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: include app pre-requisite
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq

- name: Restart nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes